### ISSUE TITLE
Create a Shared Realtime Checklist

### ISSUE THREAD

**Issue by nelsonic** [dwyl/checklist#1]
Our mission is to create a shared checklist (_or "Todo list" if you prefer_) we can all see and update in realtime. 

+ [x] `mix phx.new app`
+ [x] create schema for checklist item:
  + [x] title
  + [x] status
  + [x] priority
  + [x] time_estimate
  + [x] deadline
  + [x] schedule
  + [x] assignee
  + [x] owner

+ [x] add a few records
+ [x] sort by priority

# Status

+ [x] use ecto_enum https://github.com/gjaldon/ecto_enum for **`status`** to only allow a set of options:
  + [x] unassigned - the task is created but nobody is assigned to work on it. 
  + [x] assigned - assigned to a specific person but they are not yet working on it
  + [x] in_progress - assignee is working on the task
  + [x] awaiting_review - person who worked on the task assigned it back to the owner for review
  + [x] in_review - owner (or "QA") is reviewing the task for completion
  + [x] complete -  owner marked as complete
  + [x] dependent - dependent on another task or person
  + [x] blocked -  progress cannot continue https://github.com/dwyl/labels/issues/87

+ [x] display the status as a dropdown
+ [x] apply status `:assigned` if `assignee` is set

# Channel `#5`

+ [ ] create channel for sending realtime updates to connected viewers

**Comment by RobStallion** [comment]
```
mix phx.gen.html Ctx Todo todos title:string status:string priority:integer time_estimate:integer deadline:naive_datetime schedule:naive_datetime assignee:string owner:string
```

The above command generates the schema as well as the migration and default html for a site (and tests 🎉 ).

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/58947238-6f55c880-877f-11e9-92fd-f28f1ca4cd78.png)

we need a pre-defined list of the status ... going to use `ecto_enum`

**Comment by RobStallion** [comment]
@nelsonic I have used ecto_enum before [here](https://github.com/club-soda/club-soda-guide/blob/master/lib/cs_guide/ecto_enum.ex). Thought it might come in handy for you
