### ISSUE TITLE
Update List using Phoenix Live View

### ISSUE THREAD

**Issue by nelsonic** [dwyl/checklist#2]
Read: https://elixirschool.com/blog/phoenix-live-view
and https://github.com/dwyl/phoenix-live-view-counter

# Todo 

+ [x] Broadcast changes to checklist items using Phoenix Live View.
```
@topic  "live"
AppWeb.Endpoint.broadcast_from(self(), @topic, "update", new_state.assigns)
```

+ [x] Send Todo item `id` to handle `handle_event` so we know which Todo to update the status of.
+ [x] Update Checklist Status on the index page

**Comment by nelsonic** [comment]
This seems relevant: 
https://dennisbeatty.com/2019/04/24/how-to-create-a-todo-list-with-phoenix-liveview.html

**Comment by nelsonic** [comment]
Trying out this basic counter example: https://dennisbeatty.com/2019/03/19/how-to-create-a-counter-with-phoenix-live-view.html
On: https://github.com/dwyl/live-view-counter

**Comment by nelsonic** [comment]
Hi @RobStallion I'm attempting to in-line the status `<select>` on the todos index page:

![image](https://user-images.githubusercontent.com/194400/59106301-fd6fb180-892d-11e9-99e0-e6c9ab7247e5.png)

I can't get the `phx-change` to fire when the `<select>` is updated.
Can you help?

**Comment by nelsonic** [comment]
```elixir
          <select>
            <%= for status <- statusliststring() do %>
              <option phx-value="<%= todo.id %>_<%= status %>"
                      value="<%= status %>"
                      <%= selected(todo.status, status) %>
              >
                <%= human_readble_status(status) %>
              </option>
            <% end %>
          </select>
```

**Comment by nelsonic** [comment]
Works!!
![image](https://user-images.githubusercontent.com/194400/59113930-f6509f80-893d-11e9-9156-55d959444527.png)
